[project]
name = "controlsystem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "micropython-stm32-stubs>=1.27.0.post1",
    "mpremote>=1.27.0",
]
